import nextVitals from "eslint-config-next/core-web-vitals";

const eslintConfig = [
  ...nextVitals,
  {
    ignores: [
      ".next/**",
      "node_modules/**",
      // Generated by npm run content:build.
      "content/site-data.json",
      "public/chatbot-knowledge.txt",
      // Vercel build output (minified bundles), created by local vercel build.
      ".vercel/**",
      // Agent worktrees are separate checkouts of this repository; each lints itself.
      ".claude/worktrees/**",
      // Gitignored local scratch scripts; not part of the repository.
      "tmp/**"
    ]
  }
];

export default eslintConfig;
