"use client";
import {useCallback,useEffect,useState} from "react";
import {StaffGate} from "@/components/StaffGate";
import {staffAuthHeaders} from "@/lib/staffSession";
import {WORKS,choiceLabel} from "@/lib/percussionPreferences.mjs";
import styles from "@/app/portal/percussion-preferences/preferences.module.css";
export default function Dashboard(){return <StaffGate>{(session,signOut)=><Review session={session} signOut={signOut}/>}</StaffGate>;}
function Review({session,signOut}){
 const [rows,setRows]=useState([]),[loading,setLoading]=useState(true),[error,setError]=useState(""),[exporting,setExporting]=useState(false),[loaded,setLoaded]=useState(false);
 const load=useCallback(async()=>{setLoading(true);setLoaded(false);setRows([]);setError("");try{const response=await fetch("/api/admin/percussion-preferences",{headers:staffAuthHeaders(session),cache:"no-store"});if(response.status===401){await signOut();return;}const body=await response.json();if(!response.ok)throw new Error(body.error);setRows(body.rows);setLoaded(true);}catch(e){setError(e.message||"Unable to load.");}finally{setLoading(false);}},[session,signOut]);
 useEffect(()=>{const timer=setTimeout(load,0);return()=>clearTimeout(timer);},[load]);
 async function download(){setExporting(true);setError("");try{const response=await fetch("/api/admin/percussion-preferences?format=csv",{headers:staffAuthHeaders(session),cache:"no-store"});if(response.status===401){await signOut();return;}if(!response.ok)throw new Error((await response.json()).error);const url=URL.createObjectURL(await response.blob());const a=document.createElement("a");a.href=url;a.download="percussion-preferences-fall-2026.csv";a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}catch(e){setError(e.message||"Export unavailable.");}finally{setExporting(false);}}
 return <main className={styles.page}><h1>Percussion preferences</h1><p>Private director view · Fall 2026. Preferences are not assignments.</p>{loading?<p role="status">Loading current roster…</p>:loaded?<p>{rows.filter(row=>row.choices).length} of {rows.length} current students have saved preferences.</p>:null}<div className={styles.actions}><button onClick={load} disabled={loading}>Refresh</button><button onClick={download} disabled={!loaded||loading||exporting}>{exporting?"Exporting…":"Download CSV for Excel"}</button></div>{error&&<p className={styles.error} role="alert">{error}</p>}{loaded&&<div className={styles.scroll} role="region" aria-label="Student preferences table" tabIndex={0}><table><caption>All current Percussion Ensemble students, including those with no response</caption><thead><tr><th scope="col">Student</th><th scope="col">Status</th>{WORKS.map(work=><th scope="col" key={work.id}>{work.title}</th>)}<th scope="col">Last saved</th></tr></thead><tbody>{rows.map(row=><tr key={row.studentId}><th scope="row">{row.name}</th><td>{row.choices?"Saved":"No response"}</td>{WORKS.map(work=><td key={work.id}>{choiceLabel(work,row.choices?.[work.id])||"—"}</td>)}<td>{row.updatedAt?new Date(row.updatedAt).toLocaleString():"—"}</td></tr>)}</tbody></table></div>}</main>;
}
