import test from 'node:test';
import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import {WORKS,validChoices,resolveSelfStudent,directorRows,preferencesCsv} from '../lib/percussionPreferences.mjs';
const choices=Object.fromEntries(WORKS.map(work=>[work.id,work.parts[0][0]]));
const student={id:'synthetic',display_name:'Example Student',status:'active',ensemble_2026:'Percussion Ensemble',band_class_2026:'Yes'};
const link={role:'student',relationship_status:'trusted',student};
test('six works, twenty printed parts, exact required choices',()=>{assert.equal(WORKS.length,6);assert.equal(WORKS.flatMap(w=>w.parts).length,20);assert.ok(validChoices(choices));for(const work of WORKS){assert.equal(validChoices({...choices,[work.id]:null}),false);assert.equal(validChoices({...choices,[work.id]:'foreign'}),false);const missing={...choices};delete missing[work.id];assert.equal(validChoices(missing),false);}assert.equal(validChoices({...choices,studentId:'someone-else'}),false);assert.equal(validChoices([]),false);});
test('only unambiguous trusted student self identity is eligible',()=>{assert.equal(resolveSelfStudent({person_type:'student'},[link]),student);for(const person_type of ['guardian','staff','unknown'])assert.equal(resolveSelfStudent({person_type},[link]),null);for(const relationship_status of ['claimed','rejected','superseded'])assert.equal(resolveSelfStudent({person_type:'student'},[{...link,relationship_status}]),null);assert.equal(resolveSelfStudent({person_type:'student'},[{...link,role:'guardian'}]),null);assert.equal(resolveSelfStudent({person_type:'student'},[link,link]),null);for(const patch of [{status:'inactive'},{ensemble_2026:'Concert Band'},{band_class_2026:'No'}])assert.equal(resolveSelfStudent({person_type:'student'},[{...link,student:{...student,...patch}}]),null);});
test('director roster includes nonresponders and excludes responses outside current roster',()=>{const rows=directorRows([student,{...student,id:'second',display_name:'Second Student'}],[{student_id:'synthetic',choices,updated_at:'2026-09-18'},{student_id:'foreign',choices}]);assert.equal(rows.length,2);assert.equal(rows[0].choices,choices);assert.equal(rows[1].choices,null);assert.ok(preferencesCsv(rows).includes('No response'));});
test('CSV preserves quoted names and neutralizes spreadsheet formulas',()=>{const csv=preferencesCsv([{name:' =HYPERLINK("bad")',choices:null}]);assert.ok(csv.startsWith('\uFEFF'));assert.ok(csv.includes(`"' =HYPERLINK(""bad"")"`));});
test('storage and routes preserve privacy and editing boundaries',()=>{const read=p=>readFileSync(new URL('../'+p,import.meta.url),'utf8');const sql=read('supabase/migrations/202609180001_percussion_preferences.sql');assert.match(sql,/enable row level security/);assert.match(sql,/revoke all.*anon, authenticated/);assert.match(sql,/primary key \(survey_key,student_id\)/);assert.match(sql,/coalesce\(/);const route=read('app/api/portal/percussion-preferences/route.js');assert.match(route,/student_id:identity.student.id/);assert.match(route,/onConflict:"survey_key,student_id"/);assert.match(route,/Object.keys\(body\).length!==1/);assert.match(route,/headers.get\("origin"\)/);assert.match(read('app/api/admin/percussion-preferences/route.js'),/PERCUSSION_PREFERENCES_READ/);});

// Execute actual route handlers with synthetic dependency boundaries. No production writes.
async function routeHarness(overrides={}) {
 const vm=await import('node:vm');
 const src=readFileSync(new URL('../app/api/portal/percussion-preferences/route.js',import.meta.url),'utf8').replace(/^import .*;\n/gm,'').replace('export const runtime=','const runtime=').replace('export const GET=','globalThis.GET=').replace('export const PUT=','globalThis.PUT=');
 const writes=[];
 const context={URL,Date,privateJson:(body,status=200)=>({body,status}),selfStudent:async()=>({student,personId:'self'}),currentResponse:async()=>({choices,updated_at:'now'}),validChoices,SURVEY_KEY:'fall-2026',supabaseAdmin:{from:()=>({upsert:async(row,options)=>{writes.push({row,options});return {error:null};}})},...overrides};vm.runInNewContext(src,context);
 const request=(body={choices},origin='https://example.test')=>({url:'https://example.test/api/portal/percussion-preferences',headers:new Headers({origin}),json:async()=>body});return {...context,writes,request};
}
test('route rejects foreign identity input and enforces self-derived editable upsert',async()=>{const h=await routeHarness();assert.equal((await h.PUT(h.request({choices,studentId:'foreign'}))).status,400);assert.equal(h.writes.length,0);assert.equal((await h.PUT(h.request())).status,200);assert.equal((await h.PUT(h.request())).status,200);assert.equal(h.writes.length,2);assert.ok(h.writes.every(w=>w.row.student_id===student.id&&w.row.submitted_by_person_id==='self'&&w.options.onConflict==='survey_key,student_id'));});
test('route blocks unauthenticated, ineligible and cross-origin writes without storage',async()=>{for(const status of [401,403]){const h=await routeHarness({selfStudent:async()=>({status})});assert.equal((await h.GET(h.request())).status,status);assert.equal((await h.PUT(h.request())).status,status);assert.equal(h.writes.length,0);}const h=await routeHarness();assert.equal((await h.PUT(h.request({choices},'https://foreign.test'))).status,403);assert.equal(h.writes.length,0);});
test('route returns generic failure without sensitive storage details',async()=>{const h=await routeHarness({currentResponse:async()=>{throw new Error('private detail');}});const response=await h.GET(h.request());assert.equal(response.status,503);assert.equal(JSON.stringify(response).includes('private detail'),false);});
