// AUTO-GENERATED from Erika Svanoe's "Band of Heroes" - A Choose-Your-Own Musical Adventure.
// Story, text, and structure (c) Erika Svanoe / Alfred Music. Built from the free performance
// materials at https://www.erikasvanoe.com/band-of-heroes.html to accompany Ashley Band's
// performance of the work. Do not hand-edit; regenerate from the source deck.

export const slides = [
  { id: 1, kind: "cover", scene: "A Choose-Your-Own Musical Adventure", lines: ["Band of Heroes", "A “Choose Your Own”", "Musical Adventure"] },
  { id: 2, kind: "scene", scene: "A Choose-Your-Own Musical Adventure", lines: ["Once upon a time,", "in a land far,", "far away..."] },
  { id: 3, kind: "scene", scene: "A Choose-Your-Own Musical Adventure", lines: ["A Queen", "summoned her people to the palace."] },
  { id: 4, kind: "scene", scene: "A Choose-Your-Own Musical Adventure", lines: ["When all the people had gathered…"] },
  { id: 5, kind: "scene", scene: "A Choose-Your-Own Musical Adventure", lines: ["…the Queen said,", "“My crown has", "gone missing!”"] },
  { id: 6, kind: "scene", scene: "A Choose-Your-Own Musical Adventure", lines: ["“Will you help me", "find it?” she asks.", "“Will you join…"] },
  { id: 7, kind: "scene", scene: "A Choose-Your-Own Musical Adventure", lines: ["...the Band", "of Heroes?”"] },
  { id: 8, kind: "scene", scene: "A Choose-Your-Own Musical Adventure", lines: ["“Yes,” you say.", "“I will find your crown!”"] },
  { id: 9, kind: "scene", scene: "A Choose-Your-Own Musical Adventure", lines: ["The people", "around you agree", "to help as well."] },
  { id: 10, kind: "scene", scene: "A Choose-Your-Own Musical Adventure", lines: ["“Where will", "you start?” asks", "the Queen."] },
  { id: 11, kind: "scene", scene: "A Choose-Your-Own Musical Adventure", lines: ["“Will you", "search the spooky woods…"] },
  { id: 12, kind: "scene", scene: "A Choose-Your-Own Musical Adventure", lines: ["...or will you", "try the flowery fields?”"] },
  { id: 13, kind: "choice", scene: "A Choose-Your-Own Musical Adventure", lines: ["What do you choose?"], choices: [{"label": "The Spooky Woods", "target": 14}, {"label": "The Flowery Fields", "target": 48}] },
  { id: 14, kind: "title", scene: "The Spooky Woods", lines: ["THE", "Spooky Woods"] },
  { id: 15, kind: "scene", scene: "The Spooky Woods", lines: ["You carefully walk through the", "dark woods."] },
  { id: 16, kind: "scene", scene: "The Spooky Woods", lines: ["Ahead, you see", "a small house,", "covered in ivy."] },
  { id: 17, kind: "scene", scene: "The Spooky Woods", lines: ["You nervously approach", "the door…"] },
  { id: 18, kind: "scene", scene: "The Spooky Woods", lines: ["and knock", "three times."] },
  { id: 19, kind: "scene", scene: "The Spooky Woods", lines: ["The door opens", "and you see", "an old wizard!"] },
  { id: 20, kind: "scene", scene: "The Spooky Woods", lines: ["“Why do you", "bother me?", "Go away…”"] },
  { id: 21, kind: "scene", scene: "The Spooky Woods", lines: ["“Try the flowery fields, or bother the dancing fairies instead.”"] },
  { id: 22, kind: "scene", scene: "The Spooky Woods", lines: ["You walk back", "through the woods. Where do you go next?"] },
  { id: 23, kind: "choice", scene: "The Spooky Woods", lines: ["Where do you go next?"], choices: [{"label": "The Flowery Fields", "target": 24}, {"label": "The Dancing Fairies", "target": 36}] },
  { id: 24, kind: "title", scene: "The Flowery Fields", lines: ["THE", "Flowery Fields"] },
  { id: 25, kind: "scene", scene: "The Flowery Fields", lines: ["When you reach the fields, you see several gnomes pop up", "from the ground."] },
  { id: 26, kind: "scene", scene: "The Flowery Fields", lines: ["“What can we", "do for you?”", "they ask."] },
  { id: 27, kind: "scene", scene: "The Flowery Fields", lines: ["“We seek the Queen’s crown. Do you know where it is?” you ask."] },
  { id: 28, kind: "scene", scene: "The Flowery Fields", lines: ["“It was stolen by", "Gurg the Giant.", "The dancing fairies know where he is.”"] },
  { id: 29, kind: "scene", scene: "The Flowery Fields", lines: ["You walk back through the", "flowery fields."] },
  { id: 30, kind: "scene", scene: "The Flowery Fields", lines: ["You go", "to see the", "Dancing Fairies."] },
  { id: 31, kind: "title", scene: "The Dancing Fairies", lines: ["THE", "Dancing Fairies"] },
  { id: 32, kind: "scene", scene: "The Dancing Fairies", lines: ["The fairies are dancing in circles", "as you approach."] },
  { id: 33, kind: "scene", scene: "The Dancing Fairies", lines: ["“Do you know where Gurg the Giant is?” you ask."] },
  { id: 34, kind: "scene", scene: "The Dancing Fairies", lines: ["“Yes! He is hiding", "in a cave near the", "Lady of the Lake.”"] },
  { id: 35, kind: "scene", scene: "The Dancing Fairies", lines: ["Determined, you march toward the Lady of the Lake."], next: 85 },
  { id: 36, kind: "title", scene: "The Dancing Fairies", lines: ["THE", "Dancing Fairies"] },
  { id: 37, kind: "scene", scene: "The Dancing Fairies", lines: ["The fairies are dancing in circles", "as you approach."] },
  { id: 38, kind: "scene", scene: "The Dancing Fairies", lines: ["“We seek the Queen’s crown. Do you know where it is?”"] },
  { id: 39, kind: "scene", scene: "The Dancing Fairies", lines: ["“It was stolen by Gurg the Giant. He might be in the flowery fields.”"] },
  { id: 40, kind: "scene", scene: "The Dancing Fairies", lines: ["You head to the flowery fields."] },
  { id: 41, kind: "title", scene: "The Flowery Fields", lines: ["THE", "Flowery Fields"] },
  { id: 42, kind: "scene", scene: "The Flowery Fields", lines: ["When you reach the fields, you see several gnomes pop up", "from the ground."] },
  { id: 43, kind: "scene", scene: "The Flowery Fields", lines: ["“What can we", "do for you?”", "they ask."] },
  { id: 44, kind: "scene", scene: "The Flowery Fields", lines: ["“We seek Gurg the Giant. Do you know where he is?”"] },
  { id: 45, kind: "scene", scene: "The Flowery Fields", lines: ["“Yes! He is hiding", "in a cave near the", "Lady of the Lake.”"] },
  { id: 46, kind: "scene", scene: "The Flowery Fields", lines: ["You walk back through the", "flowery fields."] },
  { id: 47, kind: "scene", scene: "The Flowery Fields", lines: ["You make", "your way to", "The Lady of the Lake"], next: 85 },
  { id: 48, kind: "title", scene: "The Flowery Fields", lines: ["THE", "Flowery Fields"] },
  { id: 49, kind: "scene", scene: "The Flowery Fields", lines: ["When you reach the fields, you see several gnomes pop up", "from the ground."] },
  { id: 50, kind: "scene", scene: "The Flowery Fields", lines: ["“Why are you bothering us?” they ask. “Go away!”"] },
  { id: 51, kind: "scene", scene: "The Flowery Fields", lines: ["“We seek the Queen’s crown. Do you", "know where it is?”"] },
  { id: 52, kind: "scene", scene: "The Flowery Fields", lines: ["“No! Try the spooky woods or the dancing fairies instead.”"] },
  { id: 53, kind: "scene", scene: "The Flowery Fields", lines: ["You walk back through the flowery fields. Where do you go next?"] },
  { id: 54, kind: "choice", scene: "The Flowery Fields", lines: ["Where do you go next?"], choices: [{"label": "The Spooky Woods", "target": 55}, {"label": "The Dancing Fairies", "target": 70}] },
  { id: 55, kind: "title", scene: "The Spooky Woods", lines: ["THE", "Spooky Woods"] },
  { id: 56, kind: "scene", scene: "The Spooky Woods", lines: ["You carefully", "walk through the", "dark woods."] },
  { id: 57, kind: "scene", scene: "The Spooky Woods", lines: ["Ahead, you see", "a small house", "covered in ivy."] },
  { id: 58, kind: "scene", scene: "The Spooky Woods", lines: ["You nervously approach", "the door…"] },
  { id: 59, kind: "scene", scene: "The Spooky Woods", lines: ["and knock", "three times."] },
  { id: 60, kind: "scene", scene: "The Spooky Woods", lines: ["The door opens", "and you see", "an old wizard!"] },
  { id: 61, kind: "scene", scene: "The Spooky Woods", lines: ["“We seek the Queen’s crown. Can you", "help us?” you ask."] },
  { id: 62, kind: "scene", scene: "The Spooky Woods", lines: ["“It was stolen by", "Gurg the Giant.", "The dancing fairies know where he is.”"] },
  { id: 63, kind: "scene", scene: "The Spooky Woods", lines: ["You walk", "back through", "the woods..."] },
  { id: 64, kind: "scene", scene: "The Spooky Woods", lines: ["…and go", "to see the", "Dancing Fairies"] },
  { id: 65, kind: "title", scene: "The Dancing Fairies", lines: ["THE", "Dancing Fairies"] },
  { id: 66, kind: "scene", scene: "The Dancing Fairies", lines: ["The fairies are dancing in circles", "as you approach."] },
  { id: 67, kind: "scene", scene: "The Dancing Fairies", lines: ["“Do you know where Gurg the Giant is?” you ask."] },
  { id: 68, kind: "scene", scene: "The Dancing Fairies", lines: ["“Yes! He is hiding", "in a cave near the", "Lady of the Lake.”"] },
  { id: 69, kind: "scene", scene: "The Dancing Fairies", lines: ["You march", "toward the", "Lady of the Lake."], next: 85 },
  { id: 70, kind: "title", scene: "The Dancing Fairies", lines: ["THE", "Dancing Fairies"] },
  { id: 71, kind: "scene", scene: "The Dancing Fairies", lines: ["The fairies are dancing in circles", "as you approach."] },
  { id: 72, kind: "scene", scene: "The Dancing Fairies", lines: ["“We seek the Queen’s crown. Do you know where it is?” you ask."] },
  { id: 73, kind: "scene", scene: "The Dancing Fairies", lines: ["“It was stolen by Gurg the Giant. He might be in the spooky woods.”"] },
  { id: 74, kind: "scene", scene: "The Dancing Fairies", lines: ["You head", "toward the", "spooky woods."] },
  { id: 75, kind: "title", scene: "The Spooky Woods", lines: ["THE", "Spooky Woods"] },
  { id: 76, kind: "scene", scene: "The Spooky Woods", lines: ["You carefully walk through the", "dark woods."] },
  { id: 77, kind: "scene", scene: "The Spooky Woods", lines: ["Ahead, you see", "a small house", "covered in ivy."] },
  { id: 78, kind: "scene", scene: "The Spooky Woods", lines: ["You nervously approach", "the door…"] },
  { id: 79, kind: "scene", scene: "The Spooky Woods", lines: ["and knock", "three times."] },
  { id: 80, kind: "scene", scene: "The Spooky Woods", lines: ["The door opens", "and you see", "an old wizard!"] },
  { id: 81, kind: "scene", scene: "The Spooky Woods", lines: ["“Do you know where Gurg the Giant is?” you ask."] },
  { id: 82, kind: "scene", scene: "The Spooky Woods", lines: ["“Yes! He is hiding", "in a cave near the", "Lady of the Lake.”"] },
  { id: 83, kind: "scene", scene: "The Spooky Woods", lines: ["You walk back through the woods…"] },
  { id: 84, kind: "scene", scene: "The Spooky Woods", lines: ["…and head towards The Lady", "of the Lake"], next: 85 },
  { id: 85, kind: "title", scene: "The Lady of the Lake", lines: ["THE", "Lady of the Lake"] },
  { id: 86, kind: "scene", scene: "The Lady of the Lake", lines: ["As you approach the lake, a woman rises from the water."] },
  { id: 87, kind: "scene", scene: "The Lady of the Lake", lines: ["“I know you", "seek to return the crown,” she says."] },
  { id: 88, kind: "scene", scene: "The Lady of the Lake", lines: ["“To help you in", "your fight you", "may choose…"] },
  { id: 89, kind: "scene", scene: "The Lady of the Lake", lines: ["…a mighty sword!"] },
  { id: 90, kind: "scene", scene: "The Lady of the Lake", lines: ["or", "a magical whip!"] },
  { id: 91, kind: "choice", scene: "The Lady of the Lake", lines: ["What do you choose?"], choices: [{"label": "A Mighty Sword", "target": 92}, {"label": "A Magical Whip", "target": 92}] },
  { id: 92, kind: "scene", scene: "The Giant's Cave", lines: ["With your", "weapon, you go", "the giant’s cave."] },
  { id: 93, kind: "scene", scene: "The Giant's Cave", lines: ["“You will not", "take my crown!”", "Gurg shouts as he prepares for battle."] },
  { id: 94, kind: "scene", scene: "The Giant's Cave", lines: ["You fight the", "giant with your", "weapon in hand."] },
  { id: 95, kind: "scene", scene: "The Giant's Cave", lines: ["“You’ll never", "defeat me!”", "he shouts."] },
  { id: 96, kind: "scene", scene: "The Giant's Cave", lines: ["You fight", "the giant with", "all your might…"] },
  { id: 97, kind: "scene", scene: "The Giant's Cave", lines: ["The battle", "goes back", "and forth…"] },
  { id: 98, kind: "scene", scene: "The Giant's Cave", lines: ["Until the giant", "steps back and", "drops the crown.", "“I give up!” he cries."] },
  { id: 99, kind: "scene", scene: "Victory", lines: ["Victory!"] },
  { id: 100, kind: "scene", scene: "Victory", lines: ["You return", "the crown to", "the Queen."] },
  { id: 101, kind: "scene", scene: "Victory", lines: ["“Thank you,”", "she says.", "“You truly are…"] },
  { id: 102, kind: "scene", scene: "Victory", lines: ["A Band of Heroes!"], end: true },
];
